[versions]
# Jsonschema2pojo processor
# Versions: https://github.com/joelittlejohn/jsonschema2pojo/releases
processor-jsonschema2pojo = "1.3.3"

[libraries]
# Plugin Schema processors
jsonschema2pojo = { module = "org.jsonschema2pojo:jsonschema2pojo-core", version.ref = "processor-jsonschema2pojo" }
