name: Android Sample

on: [pull_request]

jobs:
  buildDemo:
    name: Build Demo JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android
    strategy:
      matrix:
        java_version: [1.8, 11, 15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Build project
        run: ./gradlew assembleDebug

  buildDevelopment:
    name: Build Dev JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/androidDev
    strategy:
      matrix:
        java_version: [1.8, 11, 15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Build project
        run: ./gradlew assembleDebug