name: Blocking Issues

on:
  issues:
    types: [opened, edited, deleted, transferred, closed, reopened]
  pull_request_target:
    types: [opened, edited, closed, reopened]
    
jobs:
  blocking_issues:
    runs-on: ubuntu-latest
    name: Checks for blocking issues
    
    steps:
      - uses: Levi-Lesches/blocking-issues@v2
        with:
          # Optional: Choose an existing label to use instead of creating a new one.
          # If the label cannot be found, the default one will be created and used.
          # The default is: "blocked" (black).
          use-label: "blocked issue"
