name: Check Spotless

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths:
      - "**/*.java"
      - "**/*.xml"
      - "**/*.json"
      - "**/*.kt"
      - "**/*.kts"
      - "**/*.yml"
      - "**/*.yaml"

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('spotless-ci-main-{0}', github.sha) || format('spotless-ci-{0}', github.ref) }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  spotless-check:
    name: Spotless check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 11 ]
        distribution: [ "zulu"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.distribution }} ${{ matrix.java }}
        uses: actions/setup-java@v3.10.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: gradle
      - run: ./gradlew spotlessCheck --warning-mode all --no-daemon -Porg.jsonschema2dataclass.internal.no-git-version=true
